### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by ikostrikov** [torch/cwrap#12]
Hi! Thanks for the package!

I'm trying to run the example provided in the documentation:

``` lua
wrap = require 'cwrap'

interface = wrap.CInterface.new()

interface:wrap(
    "numel", -- the Lua name
    "numel", -- the C function name, here the same
    -- now we describe the 'arguments' of the C function
    -- (or possible returned values)
    {
        {name="DoubleTensor"},
        {name="int", creturned=true} -- this one is returned by the C function
    }
)

print(interface:tostring())
```

But I get an error:

``` bash
cwrap/cinterface.lua:216: unknown type DoubleTensor
```

**Comment by soumith** [comment]
See the last paragraph here: https://github.com/torch/cwrap/blob/master/doc/highlevelinterface.md#wrapluaname-cfunction-arguments-

That example is not given as an isolated runnable one, but more to preface the document with an example at the top that is referred to afterwards.
