### ISSUE TITLE
Debian package of cwrap module

### ISSUE THREAD

**Issue by cdluminate** [torch/cwrap#13]
@borisfom @soumith 

I'm working on on Torch Debian packaging, and now I have successfully built `lua-torch-cwrap` package locally. I'll upload it some time later.

This partially solves https://github.com/torch/distro/issues/70

BTW, I wish torch upstream can make releases so I can write some files named `watch`, which automatically tracks upstream updates, so we can update corresponding modules in time.

Thanks.

**Comment by cdluminate** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826528

**Comment by cdluminate** [comment]
FYI, I currently use such version for cwrap package: `0~20160222-gdbd0a62`, where the `HEAD` commit hash is following `-g`, and the date is the latest commit date.

**Comment by cdluminate** [comment]
packaging repo is here:
http://anonscm.debian.org/cgit/debian-science/packages/lua-torch-cwrap.git/

package is currently pending for review:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826704

**Comment by cdluminate** [comment]
As an icebreaker the first torch module landed onto the Debian archive -- `cwrap` is available for Debian/sid now.

https://tracker.debian.org/pkg/lua-torch-cwrap

Marking this issue as done. /mentioning https://github.com/torch/distro/issues/70

**Comment by borisfom** [comment]
@cdliminate: Superb! DO you know how I should tweak my apt-get to be able to get those source packages via apt-get ?

**Comment by cdluminate** [comment]
@borisfom I post the answer here https://github.com/torch/distro/issues/70#issuecomment-239334992
